name: Build Zygisk Module

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # v3에서 v4로 수정
        with:
          submodules: 'recursive'

      - name: Set up JDK
        uses: actions/setup-java@v4 # v3에서 v4로 수정
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
         name: Zygisk-Module
        # 경로를 프로젝트 루트의 out 폴더나 zip 파일이 생성되는 곳으로 변경
         path: out/*.zip
